LXI H,8001H
MVI A,09//MOVE THE DIDGIT AT ONE'S PLACE OF THE FIRST NUMBER TO THE ACCUMULATOR 
ADI 02//ADD IMMEDIATE THE DIDGIT AT ONE'S PALCE OF THE SECOND NUMBER
CPI 09//COMPARE THE VALUE STORED IN ACCUMULATOR WITH 9
JNC A//IF ACCUMULATOR VALUE IS GREATER THAN 9
JC B//IF ACCUMULATOR VALUE IS LESS THAN 9
A:
ADI 06//ADD 6 WITH ACCUMULATOR VAUE TO MAKE IT DECIMAL
JMP B
B:
MOV B,A//STORE THE SUM IN REG B
MVI A,70//MOVE THE DIGIT AT TENTH'S PLACE OF THE FIRST NUMBER MULTIPLIED BY 10 TO THE ACCUMULTOR
ADI 40//ADD THE DIGIT AT TENTH'S PLACE OF THE SECOND NUMBER MULTIPLIED BY 10
JC F//IF THE SUM PRODUCES A CARRY
CPI 90//COMPARE 90 AS NOW WE ARE COMPUTING AT TENTH'S PLACE
JNC C//IF ACCUMULATOR VALUE IS GREATER THAN 90
JC D//IF NOT
C:
ADI 60//ADD 60 TO MAKE THE SUM DECIMAL
JC E//IF THE SUM PRODUCES A CARRY
MVI D,00//SAVE NO CARRY IN REG D
JMP D
D:
ADD B//ADD THE SUM OF DIGITS AT ONE'S PLACE WITH ACC
STA 8000H//STORE THE ACCUMULATOR VALUE IN MEM 8000H
HLT
E:
MVI D,01//SAVE THE CARRY IN REG D
MOV M,D
JMP D
F:
MVI E,01//SAVE THE CARRY IN REG E
MOV M,E
JMP C//IT IS OBVIOUSLY GREATER THAN 90 SO NO NEED TO COMAPRE
//HLT